### ISSUE TITLE
Package funcionado?

### ISSUE THREAD

**Issue by guilhermedecampo** [Germinadora/meteor-iugu#1]
Eai galera tudo bem? 

O que precisa ser feito para finalizar o package?

Abraços,

**Comment by fabianoxyz** [comment]
Fala, Guilherme! Tudo bem e você?

Faltava tudo ainda. Agora falta quase tudo... hehe!

Extrai um código hoje e adicionei no package. Ele já cobre a criação dos customers, criação do token de pagamento, criação de método de pagamento (onde você guarda o cartão do cliente no Iugu) e pagamentos com CC e boleto.

Tem também a lib js padrão do Iugu para o front-end, onde têm validações e algumas outras coisas.
Ainda tenho alguns códigos que posso extrair (um modelo de cartão e esses tipos de coisas), mas preciso normalizar antes.

Você quer ajudar a manter o pacote? Está precisando de algo para integração?
Qualquer ajuda, se precisar, pode falar comigo.

Abraços e desculpe pela demora na resposta!!

Fabiano

**Comment by juanbernabo** [comment]
Pessoal,

Fechei o pacote e estou usando ele em um outro projeto
http://unline.meteor.com alem do mais esta publicado já em
https://atmospherejs.com/germinadora/iugu

Tive varias complicações, e teve que iterar para burro, mais deu certo.

Abraços,
Juan.

Em 26 de abril de 2014 01:31, Fabiano Oliveira notifications@github.com
escreveu:

> Fala, Guilherme! Tudo bem e você?
> 
> Faltava tudo ainda. Agora falta quase tudo... hehe!
> 
> Extrai um código hoje e adicionei no package. Ele já cobre a criação dos
> customers, criação do token de pagamento, criação de método de pagamento
> (onde você guarda o cartão do cliente no Iugu) e pagamentos com CC e boleto.
> 
> Tem também a lib js padrão do Iugu para o front-end, onde têm validações e
> algumas outras coisas.
> Ainda tenho alguns códigos que posso extrair (um modelo de cartão e esses
> tipos de coisas), mas preciso normalizar antes.
> 
> Você quer ajudar a manter o pacote? Está precisando de algo para
> integração?
> Qualquer ajuda, se precisar, pode falar comigo.
> 
> Abraços e desculpe pela demora na resposta!!
> 
> Fabiano
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Germinadora/meteor-iugu/issues/1#issuecomment-41459608
> .

## 

http://www.teamware.com.br

_Juan Esteban Bernabó_
Tel: +55 11 3170 3240
Cel: +55 11 9473 72735
Skype: jbernab
GTalk: juan.bernabo@teamware.com.br
Website: www.teamware.com.br

**Comment by guilhermedecampo** [comment]
Fera esse unline Juan! ;)

Vou testar!

**Comment by guilhermedecampo** [comment]
Todo mundo já ficou puto de ficar na fila pra comprar fichas =)

Nos EUA a gente tentou um aplicativo para comprar bebidas nos Bares de SF, chamava Drinkzy.
Não deu muito certo, porque culturalmente os bartenders não gostam. Principalmente pela gorjeta.

Boa sorte ai!! =)
Um feedback bobo p/ o sistema: o placeholder para a data de expiração está no format MM/AA mas o IUGU aceita só o format MM/AAAA. 

Abraços,
